### ISSUE TITLE
Error creating email with HTML template lookup

### ISSUE THREAD

**Issue by andreaPorini** [DigitalFlow/Xrm-Html-Templating#7]
Hi Florian,

We encountered this issue trying to create an email by interface, populating the HTML template lookup.
This is the error log:

```
Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: System.ServiceModel.Security.SecurityNegotiationException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #B614A324Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>b3e0fd67-0935-48eb-9c7a-82b98ae198e6</ActivityId>
  <ErrorCode>-2147204345</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>System.ServiceModel.Security.SecurityNegotiationException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #B614A324</Message>
  <Timestamp>2019-05-15T09:19:36.3661325Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource>SdkClientCommunication</ExceptionSource>
  <InnerFault>
    <ActivityId>b3e0fd67-0935-48eb-9c7a-82b98ae198e6</ActivityId>
    <ErrorCode>-2147220970</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>System.Security.Authentication.AuthenticationException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #9D0F770F</Message>
    <Timestamp>2019-05-15T09:19:36.3661325Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault>
      <ActivityId>b3e0fd67-0935-48eb-9c7a-82b98ae198e6</ActivityId>
      <ErrorCode>-2147220970</ErrorCode>
      <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
      <Message>System.ComponentModel.Win32Exception: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #84AE4E4E</Message>
      <Timestamp>2019-05-15T09:19:36.3661325Z</Timestamp>
      <ExceptionRetriable>false</ExceptionRetriable>
      <ExceptionSource i:nil="true" />
      <InnerFault i:nil="true" />
      <OriginalException i:nil="true" />
      <TraceText i:nil="true" />
    </InnerFault>
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException>System.ServiceModel.Security.SecurityNegotiationException: A call to SSPI failed, see inner exception. ---&gt; System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---&gt; System.ComponentModel.Win32Exception: The target principal name is incorrect
   --- End of inner exception stack trace ---
   at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty&amp; remoteSecurity)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty&amp; remoteSecurity)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgrade(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgrade(StreamUpgradeInitiator upgradeInitiator, IConnection&amp; connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeoutHelper&amp; timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper&amp; timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper&amp; timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)
   at System.ServiceModel.ICommunicationObject.Open()
   at Microsoft.Crm.Sandbox.SandboxClientBase`1.Open()
   at Microsoft.Crm.Sandbox.SandboxClientBase`1.get_Proxy()
   at Microsoft.Crm.Sandbox.SandboxOrganizationService.Execute(String operation, Byte[] serializedRequest, Object sandboxTraceSettingsObj)</OriginalException>
  <TraceText>Initiating interpreter
Processing handler Not
Processing handler IsNull
Processing handler Value
Successfully processed handler Value
Successfully processed handler IsNull
Successfully processed handler Not
Initiating interpreter
Processing handler Value</TraceText>
</OrganizationServiceFault>

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Crm.Sandbox.ISandboxHost.ExecuteAndReturnTraceInfo(SandboxCallInfo callInfo, SandboxPluginExecutionContext requestContext, Guid pluginAssemblyId, Int32 sourceHash, String assemblyName, Guid pluginTypeId, String pluginTypeName, String pluginConfiguration, String pluginSecureConfig, String assemblyContents, Boolean returnTraceInfo)
   at Microsoft.Crm.Sandbox.SandboxPlugin.Execute(SandboxClient client, SandboxCallTracker callTracker, IExecutionContext requestContext, String assemblyContents, Boolean returnTraceInfo)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)

```

What could that be? 

Thank you,
Best regards

Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

I can't see the exact error from your trace, but XTL was definetly running. 
Could you share the placeholders that you used inside the template? And is it working if you create the template using a different approach.

If you're submitting your data early bound, you could also try if using late binding solves your issues.
Third party assemblies don't know custom early bindings, so this can cause issues as well.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

Did you solve your issue?

Kind Regards,
Florian

**Comment by andreaPorini** [comment]
Hi @DigitalFlow,

Sorry for the delay. Are you assuming that our custom dlls, written in Early Bound, could cause the problem? Here the screenshot of our template:

![image](https://user-images.githubusercontent.com/45461747/58946270-cd85aa00-8785-11e9-88ff-72bfed67efd1.png)

This only occurs when we try to insert by Email form the lookup on HTML Templates. On the contrary, when we create an Email via Workflow and we specify in that lookup the HTML Template, everything works fine.

Thank you for your reply,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

Yes that's correct.
There's an issue in how CRM handles the plugin pipeline.
Sometimes we saw, that when Plugins set the target to an Early Binding object, following open source plugins which can not know the early bindings fail to receive the target.

But did I understand you correctly, you're only having issues when selecting the template on a plain form for a new email?
That would be strange, I never saw issues in this.
Is it possible, that there is a custom plugin with early bindings that checks on the depth property to be <= 1?
Workflows seem to increase the Depth as well, so that might be my first guess.

Kind Regards,
Florian
If one of your plugins inserts

**Comment by andreaPorini** [comment]
Hi @DigitalFlow ,

We solved the issue by registering the plugin assembly in Isolation = None. By doing that, from an email form now it's possible to insert html template value and trigger the parse.

Thank you anyway for your support and patience,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini ,

Glad you got it solved, you're welcome.
Normally there is nothing that explicitly needs Isolation = None, but good if it works for you.

Kind Regards,
Florian
